### ISSUE TITLE
Proposal: Interpolated Parameterization

### ISSUE THREAD

**Issue by S-E-F** [surrealdb/surrealdb.net#13]
One of my personal favorite ways to deal with SQL is using interpolated strings to deal with parameters. The risk of SQL injection can be nullified by defining a special `InterpolatedStringHandler`. I've implemented this before in internal projects, and in a toy project of mine for postgres.

The tradeoff is that methods that accept parameters (`query` and `live`) would need to commit to this interpolated string handler only, not accepting regular strings with parameter objects anymore (so as to prevent accidental injection by previously interpolated strings that have since been interpolated into an actual string).

Ill put up some examples in a bit.

**Comment by S-E-F** [comment]
An example of querying with interpolation:

```csharp
var published = true;
var tags = new string[] { "surrealdb", "dotnet" };
var posts = await client.Query<Post>($"""
    SELECT *
    FROM post
    WHERE published = {published}
    AND tags CONTAINSALL {tags}
    """);
```

The driver will then use a Surreal-specific `InterpolatedStringHandler` to handle escaping for safety, and potentially even circumvent the allocation of a query string altogether and directly prepare the byte buffer to be sent over HTTP/WS for performance. The generated json would look similar to:

```json
{
  "method": "query",
  "params": ["SELECT *\nFROM post\nWHERE published = $p_published\nAND tags CONTAINSALL $p_tags",
  {
    "p_published": true,
    "p_tags": ["surrealdb", "dotnet"]
  }
}
```

To make this work safely, we would preferably drop the `Query(string)` overload to prevent the following situation:

```csharp
var injection = "; REMOVE USER root -- or whatever you want";
var oops = $"""
    SELECT * FROM post WHERE tags CONTAINSALL {injection}
    """;
var posts = await client.Query(oops);
```
In this example, the interpolation occurs outside the scope of the method call, at which point the compiler will use the `DefaultInterpolatedStringHandler` (the one used normally), which will not parameterize the query safely and create a regular `string`.

If we allow the `Query(string)` overload, the user might shoot themselves in the foot. But if we only allow the interpolated overload e.g. `Query(SurrealInterpolatedStringHandler)` the compiler would disallow regular strings from being passed in, protecting the user from making the mistake.

There are ways to circumvent this by allocating the interpolated string handler manually and passing that in, but at that it's safe to assume the user knows what they are doing.

In terms of DX, even if we don't allow the `Query(string)` overload, users would not necessarily need to keep the interpolation in mind; as the `Query(SurrealInterpolatedStringHandler` could be called (even without parameters) by putting the familiar `$` in front of the string, which is how the compiler is instructed to use the interpolation overload.

```csharp
var posts = await client.Query($"SELECT * FROM post");
                              ^^^
                               | The $ becomes mandatory
```

**Comment by S-E-F** [comment]
The only public example I have is one of my [toy projects](https://github.com/S-E-F/squeel), but I'm doing more than just interpolation here so the idea is a lot harder to follow (it's a source generator that also validates queries at compile time, and the interpolation logic is source generated as well).

**Comment by Odonno** [comment]
This is interesting stuff indeed. Reminded me of Dapper in a way.

First, I can understand the will to use interpolated string to prevent developer bad practices when using standard string (non interpolated). However, I think we should let developers have the ability to use a simple string as just `SELECT * FROM myTable;` or creating a `string` in a previous context. I think the best option here would be to create a Roslyn Analyzer that will detect the input of the `Query` method and trigger a warning (or error) to offer guidance on how to do proper parameterization.

GIven your example, I would prefer the use of indexed parameters in order to not interfere with the existing `params` that can be consumed either from the `Set` method or directly set inside the `Query` method. And it will reduce the string length as a secondary benefit. So, it should give something like `SELECT *\nFROM post\nWHERE published = $0\nAND tags CONTAINSALL $1`. Other than that, I agree that using parameters this way gives a better DX than having to create a `Dictionary` by hand.

Finally, your idea of validating queries at compile time is interesting. I suppose simple queries can be easily ran and checked against a SurrealDB in-memory instance running in a background process. I am curious about string parameterization, I suppose you would have to take random values according to the parameter types?

**Comment by S-E-F** [comment]
The toy project I referenced earlier is inspired by rust's sqlx crate, so that may be the best way to look for proper/robust ideas. I'm checking parameters currently by simply generating data based on the type, but there are circumstances where this won't work (constraints etc).

Note that since it's a toy project, I haven't explored the ins and outs of what is possible (and more importantly what isn't).

A roslyn analyzer as opposed to a forcedly correct method signature can also work. I prefer the signature approach though as a roslyn analyzer would require additional maintenance.

About the parameter naming; there isn't really an ideal solution here, people can still `SET $0 = 1` if they want to (not likely but still). I don't believe string length will have any noticeable performance hit; and if that is a concern then we should probably just wait for the binary rpc protocol 😄.
