### ISSUE TITLE
Suggestion to Standardize SDK Initialization Method Naming

### ISSUE THREAD

**Issue by dimitrianoudi** [surrealdb/surrealdb.net#39]
I've been going through the documentation for the SDK drivers for our database, and I've noticed a discrepancy in the way we initialize a new host across different languages. Specifically, in the .NET SDK, we currently use SurrealDbHttpClient.New(host) for initialization. In contrast, other languages' documentation frequently employs the .init() convention.

To maintain consistency and predictability for developers familiar with other SDKs or expecting a more standard initialisation method, I'd like to suggest renaming the method from:

`SurrealDbHttpClient.New(host)`

to

`SurrealDbHttpClient.Init(host)`

**Comment by Odonno** [comment]
Weird, on most packages, the method is named `new`. 

In Rust:
```rust
let db = Surreal::new::<Ws>("127.0.0.1:8000").await?;
```

In Golang:
```go
db, err := surrealdb.New("ws://localhost:8000/rpc")
```

For information, I tried to stay as close as possible to the Rust SDK.

And IMO, `Init` feels more confusing than `New` to me. Does `Init` also execute `Connect` or not?

**Comment by simon-curtis** [comment]
Agreed, I think it would make more sense to be able to pass this into a generic factory method and it returns `ISurrealDbClient`.

`SurrealDbClient.New("ws://localhost:8000/rpc")` should return a `SurrealDbWsClient`

I also found it quite confusing that the first parameter in the `SurrealDbWsClient` constructor doesn't accept a full connection string as the first parameter.

**Comment by Odonno** [comment]
Now, I can understand your point of view. 

I made those extra functions for the following reasons:

1. Made as `static` so that we can call the function anywhere. But we can call the `new SurrealDbClient()` everywhere too. So, not a real benefit here.
2. Trying to mimic the `let db = Surreal::new::<Ws>("127.0.0.1:8000").await?;` Rust version of the statically instance. But, like point 1, no real benefit for C# developers.
3. As a syntactic sugar form, where you only have to pass the minimum info required for the type you know you will need (WS, HTTP).

So, like you both are trying to say. If there is no value, we can definitely get rid of it.

**Comment by Odonno** [comment]
For information, those static methods are gone from at least v0.3.

**Comment by Odonno** [comment]
PR #58 for reference
