### ISSUE TITLE
AOT Strategy

### ISSUE THREAD

**Issue by simon-curtis** [surrealdb/surrealdb.net#56]
Since dotnet is putting serious emphasis on AOT at the moment and SurrealDb is going to be known for it's performance. It might be worth thinking about the strategy for how we will deliver this. Including how we handle JSON deserialisation AOT and how that is going to affect the APIs

**Comment by Odonno** [comment]
> Including how we handle JSON deserialisation AOT and how that is going to affect the APIs

That would be interesting to make benchmark for AoT indeed. To see the performance differences with the default runtime experience.

**Comment by Odonno** [comment]
Yes, I needed something like that. I have something working now on the attached PR. You can take a look if you are interested.

**Comment by Odonno** [comment]
The PR is ready now. 

I still have 6 warnings on `System.Data.Common` library related to XML serialization. I don't know where it is coming from at the moment. It may come from a dependent package but until further investigation, it can stay as-is.

I made all the required changed to make the library AOT compatible while having no breaking change for non-AOT apps.

Some notes, I may need to extend the use of Source Generators after refactoring the code:
* A Source Generator to generate all possible non-generic overloads of `Thing.From`, and if possible the object/array versions too
* A Source Generator for HttpStatusCode enum generation, instead of a consuming `Enum.Parse`
